export enum ORDER_STATUS {
    PENDING = 'PENDING',
    CHECKOUT = 'CHECKOUT',
    PAID = 'PAID',
    QUEUE = 'QUEUE',
    PROCESSING = 'PROCESSING',
    READY = 'READY',
    RESOLVED = 'RESOLVED'
}

export enum PAYMENT_STATUS {
    SUCCESS = 'SUCCESS',
    FAILED = 'FAILED'
}

export enum ROLES {
    SUPERADMIN = 'SUPERADMIN',
    ADMIN = 'ADMIN',
    TABLE = 'TABLE'
}